server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: 03eureka
          uri: https://github.com/autarklab/microservices_autobike
          search-paths: config-data
  application:
    name: config-service
